<?php

use Illuminate\Database\Seeder;

class TblJenisRegisterTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_jenis_register')->delete();
        
        \DB::table('tbl_jenis_register')->insert(array (
            0 => 
            array (
                'tbl_jenis_register_id' => '5cf33fd8-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Penyampaian Pemberitahuan Perpanjangan SPT Tahunan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'tbl_jenis_register_id' => '5cf342a8-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Penggunaan Norma Penghitungan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'tbl_jenis_register_id' => '5cf34302-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Keterangan Status Wajib Pajak',
                'jenis_register_tp' => NULL,
                'duration' => 1,
                'warning' => 1,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:11:37',
            ),
            3 => 
            array (
                'tbl_jenis_register_id' => '5cf34334-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Penelitian Bukti Penyetoran PPh atas PHTB dan Perubahan PPJB',
                'jenis_register_tp' => NULL,
                'duration' => 3,
                'warning' => 2,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'tbl_jenis_register_id' => '5cf34366-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan SKB PPH Final PHTB',
                'jenis_register_tp' => NULL,
                'duration' => 3,
                'warning' => 2,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'tbl_jenis_register_id' => '5cf3438e-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Surat Keterangan Fiskal',
                'jenis_register_tp' => NULL,
                'duration' => 3,
                'warning' => 2,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'tbl_jenis_register_id' => '5cf343b6-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Perubahan Metode Pembukuan / Tahun Buku',
                'jenis_register_tp' => NULL,
                'duration' => 14,
                'warning' => 10,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'tbl_jenis_register_id' => '5cf343d4-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Penundaan Pembayaran',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'tbl_jenis_register_id' => '5cf34406-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pengurangan Angsuran PPh Pasal 25',
                'jenis_register_tp' => NULL,
                'duration' => 30,
                'warning' => 21,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'tbl_jenis_register_id' => '5cf34424-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Penggunaan Mesin Teraan Materai',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'tbl_jenis_register_id' => '5cf3444c-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pemusatan PPN',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'tbl_jenis_register_id' => '5cf3446a-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pemindahbukuan',
                'jenis_register_tp' => NULL,
                'duration' => 30,
                'warning' => 21,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'tbl_jenis_register_id' => '5cf34492-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan SKB PPh Hibah Tanah / Bangunan',
                'jenis_register_tp' => NULL,
                'duration' => 10,
                'warning' => 7,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'tbl_jenis_register_id' => '5cf344b0-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Penagguhan PPN Impor',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'tbl_jenis_register_id' => '5cf344ce-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Restitusi / SKPLB',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'tbl_jenis_register_id' => '5cf344f6-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Surat Lain-lain',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:14:24',
            ),
            16 => 
            array (
                'tbl_jenis_register_id' => '5cf34514-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Laporan Penggunaan Mesin Teraan Materai',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'tbl_jenis_register_id' => '5cf3453c-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Ijin Pembubuhan Meterai dgn Sistem Komputerisasi',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'tbl_jenis_register_id' => '5cf34564-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan SKB PPh atas Bunga Deposito / Diskonto',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'tbl_jenis_register_id' => '5cf34582-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Perubahan Cara Penilaian Persediaan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'tbl_jenis_register_id' => '5cf345aa-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Mengangsur Pembayaran Hutang Pajak',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:06:17',
            ),
            21 => 
            array (
                'tbl_jenis_register_id' => '5cf345c8-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'SKB PPh atas Pengalihan Tanah#Bangunan Real Estate',
                'jenis_register_tp' => NULL,
                'duration' => 3,
                'warning' => 2,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'tbl_jenis_register_id' => '5cf345f0-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'SKB PPnBM atas pembelian Kendaraan AU Dalam Negeri',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'tbl_jenis_register_id' => '5cf3460e-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'SKB PPnBM atas Impor Kendaraan AU',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'tbl_jenis_register_id' => '5cf34636-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pengembalian Pendahuluan Kelebihan Pembayaran Pjk',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'tbl_jenis_register_id' => '5cf34672-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Ijin Pembubuhan Meterai Tek Percetakan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'tbl_jenis_register_id' => '5cf346a4-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pengalihan Saldo BM Mesin Teraan',
                'jenis_register_tp' => NULL,
                'duration' => 10,
                'warning' => 7,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'tbl_jenis_register_id' => '5cf346ea-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pengalihan Saldo BM Teknologi Cetak',
                'jenis_register_tp' => NULL,
                'duration' => 7,
                'warning' => 5,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'tbl_jenis_register_id' => '5cf34712-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pengalihan Saldo BM Komputerisasi',
                'jenis_register_tp' => NULL,
                'duration' => 7,
                'warning' => 5,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'tbl_jenis_register_id' => '5cf34730-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pengisian Saldo BM Mesin Teraan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'tbl_jenis_register_id' => '5cf3474e-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan SKB PPN atas Penyerahan BKP Tertentu',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'tbl_jenis_register_id' => '5cf34776-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan SKB PPN atas Impor BKP tertentu',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'tbl_jenis_register_id' => '5cf34794-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Merger Perusahaan Dalam Satu KPP',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'tbl_jenis_register_id' => '5cf347bc-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Legalisasi SKD',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'tbl_jenis_register_id' => '5cf347da-48e0-11ea-ad6b-a45e60e08cb9',
            'jenis_register_nm' => 'Permohonan Penentuan Angusran PPh Pasal 25 (RKAP)',
                'jenis_register_tp' => NULL,
                'duration' => 5,
                'warning' => 4,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'tbl_jenis_register_id' => '5cf347f8-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Tanggapan atas surat tegoran penagihan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:14:39',
            ),
            36 => 
            array (
                'tbl_jenis_register_id' => '5cf34820-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pengembalian SPOP/LSPOP',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'tbl_jenis_register_id' => '5cf3483e-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Penyampaian SPOP/LSPOP',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'tbl_jenis_register_id' => '5cf34866-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Penyampaian Tanggapan Klarifikasi',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'tbl_jenis_register_id' => '5cf34884-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Penyampaian SSP PBB Lembar ke-3',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:10:53',
            ),
            40 => 
            array (
                'tbl_jenis_register_id' => '5cf348a2-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Mutasi Objek Pajak',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'tbl_jenis_register_id' => '5cf348ca-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pemberitahuan Penundaan Pengembalian SPOP/LSPOP',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'tbl_jenis_register_id' => '5cf348e8-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pencetakan RPN',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'tbl_jenis_register_id' => '5cf34906-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pencetakan Ulang SPPT',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:13:00',
            ),
            44 => 
            array (
                'tbl_jenis_register_id' => '5cf3492e-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Angsur atau Tunda Bayar PBB',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'tbl_jenis_register_id' => '5cf3494c-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pengangsuran PBB',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'tbl_jenis_register_id' => '5cf3496a-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pengurangan Denda Administrasi',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'tbl_jenis_register_id' => '5cf34988-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pengembalian Kelebihan Pembayaran PBB',
                'jenis_register_tp' => NULL,
                'duration' => 240,
                'warning' => 168,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'tbl_jenis_register_id' => '5cf349b0-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Imbalan Bunga',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'tbl_jenis_register_id' => '5cf349ce-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pembetulan SPPT/SKP/STP PBB',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'tbl_jenis_register_id' => '5cf349f6-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pembatalan Penetapan sbg Wajib Pajak',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'tbl_jenis_register_id' => '5cf34a14-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Keberatan PBB',
                'jenis_register_tp' => NULL,
                'duration' => 270,
                'warning' => 189,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'tbl_jenis_register_id' => '5cf34a3c-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Laporan Atas SSP Pasal 22 Impor',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:05:15',
            ),
            53 => 
            array (
                'tbl_jenis_register_id' => '5cf34a5a-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Laporan Atas SSP pasal 22 Migas',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:05:22',
            ),
            54 => 
            array (
                'tbl_jenis_register_id' => '5cf34a78-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pertanggungjawaban Bukti Potong / Pungut',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'tbl_jenis_register_id' => '5cf34aa0-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Penjelasan Equalisasi PPh-PPN',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'tbl_jenis_register_id' => '5cf34abe-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'SKB Pemotongan dan/atau Pemungutan PPh 21/22/23',
                'jenis_register_tp' => NULL,
                'duration' => 30,
                'warning' => 21,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'tbl_jenis_register_id' => '5cf34adc-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'SKB PPh 22 Impor Emas Batangan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'tbl_jenis_register_id' => '5cf34b04-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'SPT Pembetulan diluar batas waktu pelaporan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'tbl_jenis_register_id' => '5cf34b22-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Penyampaian kelengkapan SPT Dropbox',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'tbl_jenis_register_id' => '5cf34b40-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Respon Kelengkapan SPT Tahunan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'tbl_jenis_register_id' => '5cf34b68-48e0-11ea-ad6b-a45e60e08cb9',
            'jenis_register_nm' => 'Penyampaian DTH &amp; RTH oleh Kuasa BUD (hardcopy)',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:09:36',
            ),
            62 => 
            array (
                'tbl_jenis_register_id' => '5cf34b86-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'SKTD Untuk Satu Kali Penyerahan Dalam Negeri',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'tbl_jenis_register_id' => '5cf34ba4-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'SKTD Untuk Satu Kali Impor',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'tbl_jenis_register_id' => '5cf34bcc-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pengurangan atau Penghapusan Sanksi Pajak PMK-29',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'tbl_jenis_register_id' => '5cf34bea-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Penghapusan Hasil Pemeriksaan PMK-197',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'tbl_jenis_register_id' => '5cf34c08-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pembetulan Pasal 16 UU KUP',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:07:02',
            ),
            67 => 
            array (
                'tbl_jenis_register_id' => '5cf34c30-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pencabutan permohonan dan/ pengajuan karena WP TA',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'tbl_jenis_register_id' => '5cf34c4e-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan SPMKP',
                'jenis_register_tp' => NULL,
                'duration' => 21,
                'warning' => 15,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'tbl_jenis_register_id' => '5cf34c6c-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Keberatan',
                'jenis_register_tp' => NULL,
                'duration' => 270,
                'warning' => 189,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 15:40:56',
            ),
            70 => 
            array (
                'tbl_jenis_register_id' => '5cf34c94-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Pencabutan Keberatan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'tbl_jenis_register_id' => '5cf34cb2-48e0-11ea-ad6b-a45e60e08cb9',
            'jenis_register_nm' => 'Pengurangan/Penghapusan Sanksi Admin (Ps.36(1)a)',
                'jenis_register_tp' => NULL,
                'duration' => 180,
                'warning' => 126,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:09:20',
            ),
            72 => 
            array (
                'tbl_jenis_register_id' => '5cf34cd0-48e0-11ea-ad6b-a45e60e08cb9',
            'jenis_register_nm' => 'Pengurangan/Pembatalan SKP (Ps.36(1)b)',
                'jenis_register_tp' => NULL,
                'duration' => 180,
                'warning' => 126,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:08:51',
            ),
            73 => 
            array (
                'tbl_jenis_register_id' => '5cf34cf8-48e0-11ea-ad6b-a45e60e08cb9',
            'jenis_register_nm' => 'Pengurangan/Pembatalan STP (Ps.36(1)c)',
                'jenis_register_tp' => NULL,
                'duration' => 180,
                'warning' => 126,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:09:02',
            ),
            74 => 
            array (
                'tbl_jenis_register_id' => '5cf34d16-48e0-11ea-ad6b-a45e60e08cb9',
            'jenis_register_nm' => 'Pembatalan SKP Hasil Pemeriksaan (Ps.36(1)d)',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:06:00',
            ),
            75 => 
            array (
                'tbl_jenis_register_id' => '5cf34d3e-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'SKB PPN BKP Tertentu Bersifat Strategis Impor',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'tbl_jenis_register_id' => '5cf34d5c-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pembatalan SKB PPN BKP Tertentu Bersifat Strategis',
                'jenis_register_tp' => NULL,
                'duration' => 2,
                'warning' => 1,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'tbl_jenis_register_id' => '5cf34d7a-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'SKB PPN Tertentu Bersifat Strategis Penyerahan',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'tbl_jenis_register_id' => '5cf34da2-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Permohonan Legalisasi SKD WP LN',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'tbl_jenis_register_id' => '5cf34dc0-48e0-11ea-ad6b-a45e60e08cb9',
            'jenis_register_nm' => 'Permohonan Surat Keterangan Jasa Luar Negeri (SKJLN)',
                'jenis_register_tp' => NULL,
                'duration' => 365,
                'warning' => 256,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'tbl_jenis_register_id' => '5cf34dde-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pendaftaran WP',
                'jenis_register_tp' => NULL,
                'duration' => 1,
                'warning' => 1,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:07:43',
            ),
            81 => 
            array (
                'tbl_jenis_register_id' => '5cf34e06-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Cetak NPWP Isteri',
                'jenis_register_tp' => NULL,
                'duration' => 1,
                'warning' => 1,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:04:21',
            ),
            82 => 
            array (
                'tbl_jenis_register_id' => '5cf34e24-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Cetak Ulang NPWP/ SKT/ SPPKP',
                'jenis_register_tp' => NULL,
                'duration' => 1,
                'warning' => 1,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:04:32',
            ),
            83 => 
            array (
                'tbl_jenis_register_id' => '5cf34e42-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pencabutan Pengukuhan PKP',
                'jenis_register_tp' => NULL,
                'duration' => 180,
                'warning' => 126,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'tbl_jenis_register_id' => '5cf34e6a-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Penetapan NE',
                'jenis_register_tp' => NULL,
                'duration' => 5,
                'warning' => 4,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:08:18',
            ),
            85 => 
            array (
                'tbl_jenis_register_id' => '5cf34e88-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pengaktifan NE',
                'jenis_register_tp' => NULL,
                'duration' => 5,
                'warning' => 4,
                'notification_tp' => 'NOTIFICATION_TP_0',
                'created_by' => 'seeder',
                'updated_by' => 'superadmin@mail.com',
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => '2020-02-18 21:08:10',
            ),
            86 => 
            array (
                'tbl_jenis_register_id' => '5cf34ea6-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Penghapusan WP',
                'jenis_register_tp' => NULL,
                'duration' => 180,
                'warning' => 126,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'tbl_jenis_register_id' => '5cf34ece-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Pengukuhan PKP',
                'jenis_register_tp' => NULL,
                'duration' => 1,
                'warning' => 1,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'tbl_jenis_register_id' => '5cf34eec-48e0-11ea-ad6b-a45e60e08cb9',
                'jenis_register_nm' => 'Perubahan Data WP',
                'jenis_register_tp' => NULL,
                'duration' => 1,
                'warning' => 1,
                'notification_tp' => 'NOTIFICATION_TP_1',
                'created_by' => 'seeder',
                'updated_by' => NULL,
                'created_at' => '2020-02-06 19:58:25',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}