<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'user_id' => '23435432324242',
                'user_nm' => 'pegawai 1',
                'user_tp' => 'USER_TP_3',
                'email' => '23435432324242',
                'phone' => NULL,
                'password' => '$2y$10$XAY4McVzHtaVBwpBtc9f2eH7MaSrEKJZsgcH5Diw8IPD/6uyqOIzy',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '531',
                'created_by' => 'USER0001',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-01-01 20:55:35',
                'updated_at' => '2020-01-01 20:55:35',
            ),
            1 => 
            array (
                'user_id' => '5210',
                'user_nm' => 'admin521',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$sCFce0VyrwhuOJRNJU46OOF2rETSHrOuAyzkALklkhXsKM4vgxaqG',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '521',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:26:23',
                'updated_at' => '2020-02-09 19:26:23',
            ),
            2 => 
            array (
                'user_id' => '5220',
                'user_nm' => 'admin522',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$7xdf06NpvV5cU1fHolaGqu4P7RW/B/k0R4pOI5JxAJx4mfk6VuGLO',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '522',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:23:52',
                'updated_at' => '2020-02-09 19:23:52',
            ),
            3 => 
            array (
                'user_id' => '5230',
                'user_nm' => 'admin523',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$qELNnKVD4YNkjgbt3XYmH.fnqaqvEUvFcd.WnN8WBEr/1XB2OLFRG',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '523',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:29:18',
                'updated_at' => '2020-02-09 19:29:18',
            ),
            4 => 
            array (
                'user_id' => '5240',
                'user_nm' => 'admin524',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$MaYEdX.3iTok.B6iZiLzd.epWGw2oU.mZMEZEyGUp0hcQDwkGvB3K',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '524',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:30:22',
                'updated_at' => '2020-02-09 19:30:22',
            ),
            5 => 
            array (
                'user_id' => '5250',
                'user_nm' => 'admin525',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$12vvf3giNtyUWWVA8TvOhuPynKq8lQNdAI5YJfjskKUSQDm6x6UF6',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '525',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:31:52',
                'updated_at' => '2020-02-09 19:31:52',
            ),
            6 => 
            array (
                'user_id' => '5260',
                'user_nm' => 'admin526',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$mNjFymNlgOUgFsAla3YOnew8/c5UyFdagsZlcrYZu5RwS.84rDKWe',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '526',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:52:42',
                'updated_at' => '2020-02-09 19:52:42',
            ),
            7 => 
            array (
                'user_id' => '5280',
                'user_nm' => 'admin528',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$QiG4FAgtXD371nZFtDME6uDb8gcIIl4/kl5GbLiRQqZC.eeDhGpM6',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '528',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:53:57',
                'updated_at' => '2020-02-09 19:53:57',
            ),
            8 => 
            array (
                'user_id' => '5290',
                'user_nm' => 'admin529',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$slrZ6mxHS9xqJOGg9wvOqOWPBQF7LaUMwb5T4kVs7hnR27wZsjFV2',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '529',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:55:04',
                'updated_at' => '2020-02-09 19:55:04',
            ),
            9 => 
            array (
                'user_id' => '5310',
                'user_nm' => 'admin531',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$afPQ/sIQ5vhtsClkLMgqbOSF6zgz2vgl.EVViFPT3s6arAXvBFaHi',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '531',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:55:55',
                'updated_at' => '2020-02-09 19:55:55',
            ),
            10 => 
            array (
                'user_id' => '5311',
                'user_nm' => 'lely',
                'user_tp' => 'USER_TP_3',
                'email' => '5311',
                'phone' => NULL,
                'password' => '$2y$10$FmXLpBPUS43sqiscFgHFtucHSdlhwYLg1ab0J0Bo5aRoUJH4FOVcK',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '531',
                'created_by' => 'USER0001',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-18 15:47:21',
                'updated_at' => '2020-02-18 15:47:21',
            ),
            11 => 
            array (
                'user_id' => '5320',
                'user_nm' => 'admin532',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$Yon3yA6IyjpsU0MvM6kEiOBJwAnaIlYHHsjX9BEeLYDpfyJIAwrvC',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '532',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:56:50',
                'updated_at' => '2020-02-09 19:56:50',
            ),
            12 => 
            array (
                'user_id' => '5330',
                'user_nm' => 'admin533',
                'user_tp' => 'USER_TP_2',
                'email' => '0',
                'phone' => NULL,
                'password' => '$2y$10$AN2oAzNF36Lr53TE9nb86OBFAdyqNm3fnqxubYMP2Jkx/Rv634e6S',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '533',
                'created_by' => 'superadmin@mail.com',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-09 19:21:57',
                'updated_at' => '2020-02-09 19:21:57',
            ),
            13 => 
            array (
                'user_id' => 'superadmin@mail.com',
                'user_nm' => 'Super Admin',
                'user_tp' => 'USER_TP_1',
                'email' => 'superadmin@mail.com',
                'phone' => NULL,
                'password' => '$2y$10$VyAwkfr9d/SER2EiANdS5OWgAiRydjJZYlUFr3D6b814D2hdOc.BC',
                'image' => NULL,
                'active' => 0,
                'tbl_company_id' => '531',
                'created_by' => 'USER0001',
                'updated_by' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-01-01 21:09:04',
                'updated_at' => '2020-01-01 21:09:46',
            ),
            14 => 
            array (
                'user_id' => 'USER0001',
                'user_nm' => 'Administrator',
                'user_tp' => 'USER_TP_2',
                'email' => 'admin@mail.com',
                'phone' => '62812345678',
                'password' => '$2y$10$q9xIIVswKEJg8M4GmwaIXuw3v/wVgm6ptaEwbEyGFth1PwNe3fXlu',
                'image' => NULL,
                'active' => 1,
                'tbl_company_id' => '531',
                'created_by' => NULL,
                'updated_by' => NULL,
                'remember_token' => 'DeumwlBVqqJMM1ZpqszaS4G3b9ZKkIDRhFLajhJOYcsiFlYyj5CLZMNxKeQR',
                'created_at' => '2019-11-20 07:15:31',
                'updated_at' => '2019-12-03 09:34:34',
            ),
        ));
        
        
    }
}